version: "3.9"

services:
  redis:
    image: redis:6.2.0-alpine3.13
    networks:
      - node-redis
  app:
    image: taenfn/node-redis:1.0.0
    networks:
      - node-redis
    depends_on:
      - redis
    ports:
      - "3000:3000"
    environment:
      PORT: 3000
      REDIS_HOST: redis
      REDIS_PORT: 6379

networks:
  node-redis: